/* Patches */
#include "alpha.h"
#include "boxdraw.h"
#include "font2.h"
#include "fullscreen_x.h"
#include "keyboardselect_reflow_st.h"
#include "keyboardselect_reflow_x.h"
#include "netwmicon.h"
#include "st_embedder_x.h"
#include "xresources.h"
